apiVersion: apps/v1
kind: Deployment
metadata:
  name: excelidraw-http-backend
  namespace: excelidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excelidraw-http-backend
  template:
    metadata:
      labels:
        app: excelidraw-http-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command: 
            - sh
            - -c
            - |
              until pg_isready -h excelidraw-postgres -p 5432 -U $POSTGRES_USER; do
                echo "Waiting for postgres..."
                sleep 2
              done
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: excelidraw-secret
                  key: POSTGRES_USER
      containers:
        - name: http-backend
          image: node:20-alpine
          workingDir: /app
          command: 
            - sh
            - -c
            - |
              # Install pnpm
              npm install -g pnpm
              
              # Clone the repo (you'll need to build and push your own image)
              # For now, this is a placeholder - you'll need to create Docker images
              echo "Starting HTTP backend..."
              sleep infinity
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: excelidraw-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: excelidraw-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: excelidraw-config
                  key: HTTP_PORT
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: excelidraw-http-backend
  namespace: excelidraw
spec:
  selector:
    app: excelidraw-http-backend
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP